version: "3.9"

name: userservice

services:
  userservice:
    build:
      context: ./userService
      dockerfile: Dockerfile
    depends_on:
        - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    networks:
      - my-api-net
  productservice:
    build:
      context: ./productService
      dockerfile: Dockerfile
    depends_on: 
      - postgres_db
    ports:
      - "8001:8001"
    networks:
      - my-api-net
  orderservice:
    build:
      context: ./orderService
      dockerfile: Dockerfile
    depends_on: 
      - postgres_db
    ports:
      - "8002:8002"
    networks:
      - my-api-net
  inventoryservice:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    depends_on: 
        - postgres_db
    ports: 
       - "8003:8003"
    networks:
       - my-api-net
       
  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
        - POSTGRES_USER=saim
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=userDB
    ports:
        - '5433:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net
volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:  # Define the custom network